api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    eager_loading:
        enabled: true
    swagger:
        versions: [3]
    collection:
        pagination:
            # User can decide if he wont's pagination
            # /api/Blog_posts/?pagination=true, /api/Blog_posts/?pagination=false
            page_parameter_name: _page
            client_enabled: true
            enabled_parameter_name: pagination
            # How many items per page
            # /api/Blog_posts?itemsPerPage=15
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 20
            # Partial option
            # /api/Blog_posts?partial=true, /api/Blog_posts?partial=false
            partial: false
            client_partial: true
            partial_parameter_name: 'partial'
    exception_to_status:
        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidConfirmationTokenException: 404
