api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    eager_loading:
        enabled: true
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
            page_parameter_name: _page
            client_enabled: true
            enabled_parameter_name: pagination
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 20

