vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads/uploads'
            # Deside how uploaded files would be renamed
            namer: Vich\UploaderBundle\Naming\UniqidNamer
